package com.easybidding.app.ws.ui.controller;

public enum RequestOperationName {
	ACTIVE, CREATE, UPDATE, DELETE, UPDATEUSERNAME, UPDATEPASSWORD, FORGOTPASSWORD, RESETPASSWORD, LOGOUT, BATCHINSERT, BATCHUPDATE,
	BATCHDELETE, FILESUPLOAD, SETINITIALPASSWORD
}
